# gobstonescursos/curso-LPYSD2-virtual
# Actividad 2. Lucho enciende las luces, extendido
# https://gobstones.github.io/gobstones-jr/?course=gobstonescursos/curso-LPYSD2-virtual&github=gobstonescursos/curso-LPYSD2-virtual&path=Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido

GET https://raw.githubusercontent.com/wiki/gobstones/gobstones-web/Courses.md
HTTP/2 200

GET https://api.github.com/repos/gobstones/gobstones-web-desktop/releases/latest
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/guides.json
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/assets?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 404

GET https://raw.githubusercontent.com/wiki/gobstones/gobstones-web/Courses.md
HTTP/2 200

GET https://api.github.com/repos/gobstones/gobstones-web-desktop/releases/latest
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/guides.json
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/assets?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 404

GET https://raw.githubusercontent.com/wiki/gobstones/gobstones-web/Courses.md
HTTP/2 200

GET https://api.github.com/repos/gobstones/gobstones-web-desktop/releases/latest
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/Unidades/0.Repaso/1.Lucho%20enciende%20las%20luces/cover.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/cover.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/Unidades/0.Repaso/3.F%C3%BAtbol%20de%20robots/cover.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/Unidades/0.Repaso/4.La%20m%C3%BAsica%20del%20loro/cover.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-LPYSD2-virtual/master/guides.json
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/assets?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 404

GET https://raw.githubusercontent.com/wiki/gobstones/gobstones-web/Courses.md
HTTP/2 200

GET https://api.github.com/repos/gobstones/gobstones-web-desktop/releases/latest
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/assets?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/content.gbk
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/content.gbs
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/cover.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/description.md
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/extra.gbs
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/meta.yml
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/assets/attires?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/assets/boards?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/assets/resources?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/assets/solutions?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://api.github.com/repos/gobstonescursos/curso-LPYSD2-virtual/contents/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces,%20extendido/assets/attires/Lucho%20enciende%20las%20luces?client_id=086085200026d5c54c19&client_secret=f40981be76b00e35d4437d71184f42a70d08f3a6
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/boards/Board1.gbb
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/boards/Board2.gbb
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/boards/Board3.gbb
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/resources/Imagen1-small.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/resources/Imagen1.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/resources/description.odt
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/resources/description.pdf
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/solutions/0-2-Lucho%20enciende%20las%20luces%2C%20extendido-SubeYSube.gbk
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/solutions/0-2-Lucho%20enciende%20las%20luces%2C%20extendido-SubeYSube.gbs
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/FondoLucho.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/Lucho.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/LuchoLuzApagada.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/LuchoLuzPrendida.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/LuzApagada.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/LuzPrendida.png
HTTP/2 200

GET https://raw.githubusercontent.com/gobstonescursos/curso-lpysd2-virtual/master/Unidades/0.Repaso/2.Lucho%20enciende%20las%20luces%2C%20extendido/assets/attires/Lucho%20enciende%20las%20luces/config.yml
HTTP/2 200

